# Generated by Django 5.1.4 on 2024-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_user_password_hash_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='scale',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
