# Generated by Django 5.1.4 on 2024-12-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_user_language_user_scale_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='ru', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='scale',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.IntegerField(default=0),
        ),
    ]
